services:
  spark-master:
    image: custom-spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_REST_PORT=6066
    volumes:
      - ./data:/opt/data
      - ./logs:/opt/spark/logs
    networks:
      - spark-network

  spark-worker-1:
    image: custom-spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4g
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./data:/opt/data
      - ./logs:/opt/spark/logs
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    image: custom-spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    ports:
      - "8082:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4g
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./data:/opt/data
      - ./logs:/opt/spark/logs
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-3:
    image: custom-spark:latest
    container_name: spark-worker-3
    hostname: spark-worker-3
    ports:
      - "8083:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4g
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./data:/opt/data
      - ./logs:/opt/spark/logs
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-history-server:
    image: custom-spark:latest
    container_name: spark-history-server
    hostname: spark-history-server
    ports:
      - "18080:18080"
    command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.history.HistoryServer"]
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark/logs -Dspark.history.ui.port=18080
    volumes:
      - ./logs:/opt/spark/logs
    depends_on:
      - spark-master
    networks:
      - spark-network

  spring-boot-app:
    build:
      context: .
      dockerfile: spring-boot-app/Dockerfile
    container_name: spring-boot-app
    hostname: spring-boot-app
    ports:
      - "8084:8080"
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./data:/opt/data
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

volumes:
  data:
  logs:

